### Obtener todos los productos
GET https://localhost:8443/api/productos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzQGhvdG1haWwuY29tIiwidXN1YXJpb19pZCI6MjIsImlhdCI6MTczMzA5MDU4MiwiZXhwIjoxNzMzMTU1MzgyfQ.IabjlfQtrlLcOVtSQaK0d7ggTK7qjkE-nC9Y2_6FdeE
