### Elininar un producto
DELETE https://localhost:8443/api/productos/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzQGhvdG1haWwuY29tIiwiaWF0IjoxNzMxMjE4NTk1LCJleHAiOjE3MzEyMjIxOTV9.Oa-023hgYhADhM79AAElJVBVt49hQK0E5tAhnxFIYDc
