-- DROP DATABASE db_rentaProductos;
CREATE DATABASE db_rentaProductos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE db_rentaProductos;

CREATE TABLE Usuarios (
    usuario_id INT UNSIGNED NOT NULL,
    admin_id INT UNSIGNED NULL,
    nombre VARCHAR(55) NOT NULL,
    apellido_pat VARCHAR(55) NOT NULL,
    apellido_mat VARCHAR(55) NULL,
    telefono VARCHAR(25) NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(125) NOT NULL,
    avatar VARCHAR(255) NULL,
    createdAt TIMESTAMP NULL
)  ENGINE=INNODB;
ALTER TABLE Usuarios ADD CONSTRAINT PK$ID$USERS PRIMARY KEY (usuario_id);
ALTER TABLE Usuarios MODIFY COLUMN usuario_id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE Usuarios ADD CONSTRAINT U$TEL$USERS UNIQUE (telefono);
ALTER TABLE Usuarios ADD CONSTRAINT U$MAIL$USERS UNIQUE (email);
ALTER TABLE Usuarios ADD CONSTRAINT FK$ADMIN$USER FOREIGN KEY (admin_id) REFERENCES Usuarios(usuario_id) ON DELETE SET NULL;

CREATE TABLE Categorias (
    categoria_id INT UNSIGNED NOT NULL,
    nombre VARCHAR(55) NOT NULL,
    descripcion VARCHAR(120) NULL
)  ENGINE=INNODB;
ALTER TABLE Categorias ADD CONSTRAINT PK$ID$CAT PRIMARY KEY (categoria_id);
ALTER TABLE Categorias MODIFY COLUMN categoria_id INT UNSIGNED NOT NULL AUTO_INCREMENT;

CREATE TABLE Productos (
    producto_id INT UNSIGNED NOT NULL,
    nombre VARCHAR(55) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    estado VARCHAR(15) NOT NULL,
    tarifa_renta NUMERIC(16 , 2 ) NOT NULL,
    fecha_adquisicion TIMESTAMP NOT NULL,
    imagen VARCHAR(255) NOT NULL
)  ENGINE=INNODB;
ALTER TABLE Productos ADD CONSTRAINT PK$ID$PROD PRIMARY KEY (producto_id);
ALTER TABLE Productos MODIFY COLUMN producto_id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE Productos ADD COLUMN usuario_id INT UNSIGNED NULL;
ALTER TABLE Productos ADD COLUMN categoria_id INT UNSIGNED NULL;
-- ALTER TABLE Productos MODIFY COLUMN usuario_id INT UNSIGNED NOT NULL;
-- ALTER TABLE Productos MODIFY COLUMN categoria_id INT UNSIGNED NOT NULL;
ALTER TABLE Productos ADD CONSTRAINT FK$ID$USER$PROD FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id) ON DELETE CASCADE;
ALTER TABLE Productos ADD CONSTRAINT FK$ID$CAT$PROD FOREIGN KEY (categoria_id) REFERENCES Categorias(categoria_id) ON DELETE CASCADE;
-- ALTER TABLE Productos ADD CONSTRAINT FK$ID$CAT$PROD FOREIGN KEY (categoria_id) REFERENCES Categorias(categoria_id) ON DELETE SET NULL;
ALTER TABLE Productos ADD CONSTRAINT CHK$PROD$EST CHECK (estado IN ('disponible','no disponible'));
-- ALTER TABLE Productos DROP FOREIGN KEY FK$ID$CAT$PROD;
ALTER TABLE Productos ADD COLUMN stock INT UNSIGNED NOT NULL DEFAULT 0 AFTER imagen;

CREATE TABLE Rentas (
    renta_id INT UNSIGNED NOT NULL,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    estado VARCHAR(20) NOT NULL,
    total NUMERIC(16 , 2 ) NOT NULL,
    fecha_devolucion TIMESTAMP NOT NULL
)  ENGINE=INNODB;
ALTER TABLE Rentas ADD CONSTRAINT PK$ID$PUB PRIMARY KEY (renta_id);
ALTER TABLE Rentas MODIFY COLUMN renta_id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE Rentas ADD COLUMN usuario_id INT UNSIGNED NULL;
ALTER TABLE Rentas MODIFY COLUMN usuario_id INT UNSIGNED NOT NULL;
ALTER TABLE Rentas ADD CONSTRAINT FK$ID$USER$REN FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id) ON DELETE CASCADE;
-- ALTER TABLE Rentas ADD CONSTRAINT FK$ID$USER$REN FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id) ON DELETE SET NULL;
-- ALTER TABLE Rentas DROP FOREIGN KEY FK$ID$USER$REN;
ALTER TABLE Rentas ADD CONSTRAINT CHK$REN$EST CHECK (estado IN ('pendiente','activa','completada','cancelada'));
ALTER TABLE Rentas MODIFY COLUMN fecha_devolucion TIMESTAMP NULL;

CREATE TABLE ProductoxRenta (
    cantidad INT UNSIGNED NULL
)  ENGINE=INNODB;
ALTER TABLE ProductoxRenta ADD COLUMN productxrenta_id INT UNSIGNED NOT NULL;
ALTER TABLE ProductoxRenta ADD CONSTRAINT PK$PRD$REN$ID PRIMARY KEY (productxrenta_id);
ALTER TABLE ProductoxRenta MODIFY COLUMN productxrenta_id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE ProductoxRenta ADD COLUMN producto_id INT UNSIGNED NULL;
ALTER TABLE ProductoxRenta ADD COLUMN renta_id INT UNSIGNED NULL;
ALTER TABLE ProductoxRenta MODIFY COLUMN cantidad INT UNSIGNED NOT NULL;
ALTER TABLE ProductoxRenta ADD CONSTRAINT FK$ID$PROD$PRODXREN FOREIGN KEY (producto_id) REFERENCES Productos(producto_id) ON DELETE CASCADE;
ALTER TABLE ProductoxRenta ADD CONSTRAINT FK$ID$REN$PRODXREN FOREIGN KEY (renta_id) REFERENCES Rentas(renta_id) ON DELETE CASCADE;
ALTER TABLE ProductoxRenta ADD INDEX idx_producto_renta (producto_id, renta_id);

CREATE TABLE metodoPago (
    metodopago_id INT UNSIGNED NOT NULL,
    monto NUMERIC(16 , 2 ) NOT NULL,
    fecha_pago TIMESTAMP NOT NULL,
    metodo VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL
)  ENGINE=INNODB;
ALTER TABLE metodoPago ADD CONSTRAINT PK$ID$MTDPG PRIMARY KEY (metodopago_id);
ALTER TABLE metodoPago MODIFY COLUMN metodopago_id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE metodoPago ADD COLUMN renta_id INT UNSIGNED NULL;
ALTER TABLE metodoPago ADD CONSTRAINT FK$ID$REN$MTDPG FOREIGN KEY (renta_id) REFERENCES Rentas(renta_id) ON DELETE CASCADE;
ALTER TABLE metodoPago MODIFY COLUMN renta_id INT UNSIGNED NOT NULL;
-- ALTER TABLE metodoPago ADD CONSTRAINT FK$ID$REN$MTDPG FOREIGN KEY (renta_id) REFERENCES Rentas(renta_id) ON DELETE SET NULL;
-- ALTER TABLE metodoPago DROP FOREIGN KEY FK$ID$REN$MTDPG;
ALTER TABLE metodoPago ADD CONSTRAINT CHK$MTDPG$EST CHECK (estado IN ('pendiente','completado','fallido'));
ALTER TABLE metodoPago ADD CONSTRAINT CHK$MTDPG$MET CHECK (metodo IN ('tarjeta', 'efectivo', 'transferencia'));

CREATE TABLE Notificaciones (
    notificacion_id INT UNSIGNED NOT NULL,
    mensaje VARCHAR(255) NOT NULL,
    fecha_envio TIMESTAMP NOT NULL,
    leido BOOLEAN NOT NULL DEFAULT FALSE,
    tipo VARCHAR(25) NULL
)  ENGINE=INNODB;
ALTER TABLE Notificaciones ADD CONSTRAINT PK$ID$NOT PRIMARY KEY (notificacion_id);
ALTER TABLE Notificaciones MODIFY COLUMN notificacion_id INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE Notificaciones ADD COLUMN usuario_id INT UNSIGNED NULL;
ALTER TABLE Notificaciones ADD COLUMN renta_id INT UNSIGNED NULL;
ALTER TABLE Notificaciones MODIFY COLUMN usuario_id INT UNSIGNED NOT NULL;
ALTER TABLE Notificaciones ADD CONSTRAINT FK$ID$USER$NOT FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id);
ALTER TABLE Notificaciones ADD CONSTRAINT FK$ID$REN$NOT FOREIGN KEY (renta_id) REFERENCES Rentas(renta_id) ON DELETE SET NULL;
ALTER TABLE Notificaciones ADD CONSTRAINT CHK$NOT$TIP CHECK (tipo IN ('recordatorio','vencimiento','pago pendiente', 'actualizacion'));
-- ALTER TABLE metodoPago DROP CONSTRAINT CHK$MTDPG;

-- Visualizar los constraints de la base de datos db_rentaProductos
SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE
FROM information_schema.TABLE_CONSTRAINTS
WHERE TABLE_SCHEMA = 'db_rentaProductos';

